services:
  db:
    restart: always
    image: postgres:15-alpine
    container_name: HifiPostgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  
  app:
    build: .
    image: hifibackend
    container_name: HifiBackend
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db