# Generated by Django 4.2 on 2025-06-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hificom', '0037_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='sale_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.FloatField(default=120),
        ),
    ]
