# Generated by Django 4.2 on 2025-06-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hificom', '0038_cartproduct_sale_price_order_coupon_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_charge',
            field=models.FloatField(default=0),
        ),
    ]
